server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force-response: true

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB   
# 운영환경
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://1.213.164.252:63306/SURVEY
    username: exdev
    password: exdevpwd!!