server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
    
# 운영환경
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://1.213.164.252:63306/SURVEY
    username: exdev
    password: exdevpwd!!
  
# 개발환경
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver  
#    jdbc-url: jdbc:mariadb://1.242.49.61:3306/survey
#    username: root
#    password: root